version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "cron"
      cronjob: "0 3 * * *"
      cooldown:
        default-days: 7
    groups:
      group-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(dependabot)"
    open-pull-requests-limit: 64
